# E2E specific hurl execution on boot.
services:
  ss1:
    entrypoint: [ "/usr/local/bin/init-token-and-run-entrypoint.sh" ]
    volumes:
      - ./ss1/init-token-and-run-entrypoint.sh:/usr/local/bin/init-token-and-run-entrypoint.sh:ro

  hurl:
    command: >
      --insecure
      --variables-file /hurl-src/vars.env
      --file-root /hurl-files
      /hurl-src/setup.hurl
      --very-verbose
      --retry 12
      --retry-interval 10000

